FROM centos:centos8
RUN yum install -y epel-release
RUN yum install -y ansible
COPY . /etc/ansible/roles/ansible-factorio/
COPY tests/inventory /etc/ansible/hosts
COPY tests/test.yml /root/
CMD ansible-playbook ~/test.yml -c local
